export const texts = {
  title: "Modpack Localizer Pro - 整合包汉化工坊",
  description: "一款专业(?)的 Minecraft 整合包汉化工作台。它将强大的 AI 翻译、社区资源整合与精细的手动校对、项目存读档功能深度结合，为整合包作者和玩家提供从一键自动化到完整项目管理的全流程本地化体验。",
  latest_release: "下载最新版",
  feature_showcase: "功能展示",
  manual_workbench: "手动翻译工作台",
  manual_workbench_desc: "专业的三栏式布局，方便您按模组对上千条文本进行高效的审查、编辑和校对。",
  dict_search: "社区词典查询",
  dict_search_desc: "强大的原文/译文双向模糊搜索，快速找到您需要的参考翻译。",
  features_title: "核心特性",
  features: [
    { name: "工作台模式", desc: "提供专业的“主-从-编辑器”三栏式布局，对每一条翻译进行精细审查和修改。" },
    { name: "项目存读档", desc: "可随时将工作进度保存为 .sav 项目文件，之后通过主菜单恢复工作，防止心血白费。" },
    { name: "全局词典查询", desc: "支持原文/译文双向智能模糊搜索，并深度集成到工作台中。" },
    { name: "智能翻译引擎", desc: "集成 Google Gemini API，提供高质量、可配置的 AI 翻译服务。" },
    { name: "多格式兼容", desc: "自动检测并处理模组中的 .json 和 .lang 语言文件。" },
    { name: "社区包叠加", desc: "按优先级顺序智能合并多个社区汉化包，充分利用已有成果。" },
  ],
  footer_text: "本项目采用 MIT 许可证。",
  view_on_github: "在 GitHub 上查看",
};
