// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_layout.tsx";
import * as $1 from "./routes/index.tsx";
import * as $$0 from "./islands/LanguageSwitcher.tsx";

const manifest = {
  routes: {
    "./routes/_layout.tsx": $0,
    "./routes/index.tsx": $1,
  },
  islands: {
    "./islands/LanguageSwitcher.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
